spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    hikari:
      username: sa
      password:
  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true